Repository sirius-valley/lerni-mobile, pull requests merged in 2024-02, with the labels that each got.

#44 [HOTFIX] Bottom tabs logic - Profile data - Modal position
  app.json
  src/app/(auth)/(tabs)/_layout.tsx
  src/app/(auth)/(tabs)/profile/index.tsx
  src/components/tab/TabItem/index.tsx
  src/hoc/modals/IntroModal/index.tsx
Labels: bug, hotfix

#45 [HOTFIX] Style padding fix on freetext bubble
  src/app/(auth)/pill/introduction/index.tsx
  src/components/bubbles/FreeTextAnswer/index.tsx
Labels: hotfix

#48 [LER-75] Update Profile Detail
  assets/icons/CareerIcon.tsx
  assets/icons/LocationIcon.tsx
  assets/icons/ProfessionIcon.tsx
  src/app/(auth)/(tabs)/profile/index.tsx
  src/components/common/Skeleton/SkeletonProfile/index.tsx
  src/components/profile/ProfileAccomplishments/index.tsx
  src/components/profile/ProfileDetail/index.tsx
  src/components/profile/ProfileRanking/index.tsx
  src/components/profile/utils/index.tsx
Labels: enhancement

#51 [LER-76] Questionnaire button
  src/app/(auth)/(tabs)/explore/index.tsx
  src/app/(auth)/pill/testQuestionnaire/index.tsx
  src/components/bubbles/LabeledSend/index.tsx
  src/components/bubbles/MultipleAnswer/index.tsx
  src/components/bubbles/PointsDisplay/index.tsx
  src/components/bubbles/QuestionnaireAnswer/index.tsx
  src/components/bubbles/QuestionnaireImgAnswer/Item/index.tsx
  src/components/bubbles/QuestionnaireImgAnswer/Item/styles.ts
  src/components/bubbles/QuestionnaireImgAnswer/index.tsx
  src/components/bubbles/QuestionnaireImgAnswer/styles.ts
  src/components/bubbles/SingleAnswer/index.tsx
  src/components/pill-blocks/Carousel/index.tsx
  src/components/styled/PillChoice/index.tsx
  src/components/styled/PillChoice/styles.ts
  src/components/styled/QuestionnaireChoice/index.tsx
  src/components/styled/QuestionnaireChoice/styles.ts
Labels: enhancement

#53 [LER-64] Questionnaire logic
  src/app/(auth)/(tabs)/explore/index.tsx
  src/app/(auth)/pill/testQuestionnaire/index.tsx
  src/components/bubbles/QuestionnaireImgAnswer/index.tsx
  src/components/pill/QuestionnaireRender/index.tsx
  src/hooks/useQuestionnaire.tsx
  src/redux/service/questionnaire.service.ts
  src/redux/service/types/pill.response.ts
  src/redux/slice/pill.slice.ts
  src/redux/slice/questionnaire.slice.ts
  src/redux/slice/utils.ts
  src/redux/store.ts
  src/utils/questionnaireUtils.ts
Labels: enhancement

#55 [LER-89] Integrate Program Details
  src/app/(auth)/(tabs)/explore/index.tsx
  src/app/(auth)/(tabs)/explore/programDetail/ProgramSkeleton/index.tsx
  src/app/(auth)/(tabs)/explore/programDetail/index.tsx
  src/components/program/LeaderboardRow/ThreeDots/index.tsx
  src/components/program/PillRow/index.tsx
  src/components/styled/TextInput/index.tsx
  src/redux/service/program.service.ts
  src/redux/service/types/program.response.ts
Labels: enhancement

#58 [LER-98] Integrate explore with B/E
  src/app/(auth)/(tabs)/explore/index.tsx
  src/app/(auth)/(tabs)/explore/programDetail/index.tsx
  src/app/(auth)/pill/mainPill/index.tsx
  src/components/explore/ExploreRow/index.tsx
  src/components/explore/HomeSkeleton/index.tsx
  src/components/pill/PillHeader/index.tsx
  src/components/program/ProgramCard/index.tsx
  src/redux/service/api.ts
  src/redux/service/program.service.ts
  src/redux/service/types/program.response.ts
  src/redux/slice/program.slice.ts
  src/redux/store.ts
Labels: enhancement
