Repository sirius-valley/lerni-mobile, pull requests merged in 2024-03, with the labels that each got.

#60 Hotfix/carousel img bug
  src/app/(auth)/(tabs)/explore/index.tsx
  src/app/(auth)/(tabs)/explore/pillDetail/index.tsx
  src/app/(auth)/(tabs)/explore/programDetail/index.tsx
  src/app/(auth)/(tabs)/profile/index.tsx
  src/app/(auth)/pill/mainPill/index.tsx
  src/components/bubbles/ChatBubble/index.tsx
  src/components/bubbles/CommentBubble/index.tsx
  src/components/bubbles/ImageBubble/index.tsx
  src/components/bubbles/QuestionnaireImgAnswer/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/pill-blocks/Carousel/index.tsx
  src/components/pill/PillRender/BubbleToRender/index.tsx
  src/components/pill/PillRender/index.tsx
  src/components/pill/QuestionnaireRender/QuestionnaireBubbleToRender/index.tsx
  src/components/pill/QuestionnaireRender/index.tsx
  src/components/profile/ProfileAccomplishments/index.tsx
  src/components/profile/ProfileDetail/index.tsx
  src/components/program/LeaderboardRow/index.tsx
  src/hooks/usePill.tsx
  src/hooks/useQuestionnaire.tsx
  src/redux/service/types/pill.response.ts
  src/redux/slice/pill.slice.ts
  src/redux/slice/questionnaire.slice.ts
Labels: hotfix

#62 [LER-110] Bugs from notion
  src/components/bubbles/QuestionnaireImgAnswer/index.tsx
  src/hooks/useQuestionnaire.tsx
  src/redux/slice/questionnaire.slice.ts
  src/redux/slice/utils.ts
Labels: bug

#61 [HOTFIX] Fixes over login and registration screens.
  assets/icons/ChevronLeftIcon.tsx
  src/app/(app)/login/index.tsx
  src/app/(app)/register/index.tsx
  src/components/common/MainContainer/index.tsx
Labels: hotfix

#63 [LER-BUG-10-NOTION] Questionnaire not showing read only version
  src/app/(auth)/pill/questionnaire/[questionnaireId]/index.tsx
  src/components/bubbles/QuestionnaireImgAnswer/index.tsx
  src/components/pill/QuestionnaireRender/QuestionnaireBubbleToRender/index.tsx
  src/hooks/useQuestionnaire.tsx
  src/redux/service/questionnaire.service.ts
  src/redux/slice/pill.slice.ts
  src/redux/slice/questionnaire.slice.ts
Labels: bug

#65 [LER-114] Questionnaire time to unlock
  package-lock.json
  package.json
  src/app/(auth)/(tabs)/_layout.tsx
  src/app/(auth)/(tabs)/explore/programDetail/components/PillsSection/index.tsx
  src/components/program/PillRow/index.tsx
  src/redux/service/types/program.response.ts
  src/redux/service/types/questionnaire.response.ts
  src/redux/slice/program.slice.ts
Labels: enhancement

#70 [LER] Team bugfixing
  src/app/(app)/register/index.tsx
  src/app/(auth)/(tabs)/explore/comments/[id]/index.tsx
  src/app/(auth)/(tabs)/explore/index.tsx
  src/app/(auth)/(tabs)/explore/programDetail/components/HeaderProgram/index.tsx
  src/app/(auth)/(tabs)/explore/programDetail/index.tsx
  src/app/(auth)/(tabs)/explore/searchScreen/index.tsx
  src/app/(auth)/(tabs)/profile/index.tsx
  src/app/(auth)/pill/introduction/index.tsx
  src/app/(auth)/pill/mainPill/index.tsx
  src/app/(auth)/pill/questionnaire/[questionnaireId]/index.tsx
  src/components/bubbles/FreeTextAnswer/index.tsx
  src/components/bubbles/QuestionnaireAnswer/index.tsx
  src/components/bubbles/TextBubble/index.tsx
  src/components/common/Result/FailurePill/index.tsx
  src/components/common/Result/SuccessPill/index.tsx
  src/components/pill-blocks/Carousel/index.tsx
  src/components/pill/PillHeader/index.tsx
  src/components/pill/PillMainContainer/index.tsx
  src/components/pill/QuestionnaireRender/QuestionnaireBubbleToRender/.index.tsx.swn
  src/components/pill/QuestionnaireRender/QuestionnaireBubbleToRender/.index.tsx.swo
  src/components/profile/ProfileDetail/index.tsx
  src/components/profile/ProfileRanking/index.tsx
  src/components/program/PillRow/index.tsx
  src/components/program/ProgramCard/index.tsx
  src/components/program/ProgramImage/index.tsx
  src/components/search/SearchItem/index.tsx
  src/hoc/modals/FeedbackModal/index.tsx
  src/redux/service/api.ts
  src/redux/service/program.service.ts
  src/redux/service/questionnaire.service.ts
  src/redux/service/types/pill.response.ts
  src/redux/service/types/student.response.ts
  src/redux/slice/questionnaire.slice.ts
Labels: bug

#75 [LER-117] Questions and answer
  src/app/(auth)/(tabs)/trivia/index.tsx
  src/app/(auth)/triviaScreen/battle/_layout.tsx
  src/app/(auth)/triviaScreen/battle/index.tsx
  src/app/(auth)/triviaScreen/index.tsx
  src/components/trivia/AnswerButton/index.tsx
  src/components/trivia/AnswerButton/styles.ts
  src/components/trivia/LoadingVersus/VersusContainer/index.tsx
  src/components/trivia/Question/index.tsx
  src/components/trivia/Question/styles.ts
  src/components/trivia/styles.ts
  src/hooks/useTrivia.tsx
  src/redux/service/trivia.service.ts
  src/redux/service/types/trivia.response.ts
  src/redux/slice/trivia.slice.ts
  src/redux/store.ts
Labels: enhancement

#79 [LER-124] Trivia history
  src/app/(auth)/(tabs)/trivia/TriviaHistory/index.tsx
  src/app/(auth)/(tabs)/trivia/TriviaHistory/mocked/index.tsx
  src/app/(auth)/(tabs)/trivia/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/styled/styles.ts
  src/components/trivia/TriviaHistoryCard/Skeleton/TriviaHistorySkeleton.tsx
  src/components/trivia/TriviaHistoryCard/index.tsx
  src/redux/service/trivia.service.ts
  src/redux/service/types/trivia.response.ts
  src/utils/theme.tsx
Labels: enhancement

#80 [LER-125] Quiz logic hook
  assets/icons/TriviaResultFailedIcon.tsx
  assets/icons/TriviaResultFinishedIcon.tsx
  assets/icons/TriviaResultSuccessIcon.tsx
  package-lock.json
  package.json
  src/app/(auth)/triviaScreen/battle/_layout.tsx
  src/app/(auth)/triviaScreen/battle/index.tsx
  src/app/(auth)/triviaScreen/index.tsx
  src/components/trivia/Countdown/index.tsx
  src/components/trivia/LoadingVersus/index.tsx
  src/components/trivia/PlayerStatus/index.tsx
  src/components/trivia/PlayersHeader/index.tsx
  src/components/trivia/TriviaHistoryCard/Skeleton/TriviaHistorySkeleton.tsx
  src/components/trivia/TriviaResult/index.tsx
  src/components/trivia/TriviaResult/styles.ts
  src/components/trivia/TriviaTriangleBackground/index.tsx
  src/hooks/useTrivia.tsx
  src/redux/service/trivia.service.ts
  src/redux/service/types/trivia.response.ts
  src/redux/slice/trivia.slice.ts
  src/utils/quizUtils.ts
Labels: enhancement

#82 [BUGFIX] Trivia several bugfixes
  integration-tests/android/locators/login.ts
  integration-tests/android/tests/app.ts
  integration-tests/android/tests/login.ts
  integration-tests/android/utils/init.ts
  integration-tests/common/commands/login.ts
  integration-tests/common/locators/types.ts
  integration-tests/common/projectCapabilities.ts
  integration-tests/ios/locators/login.ts
  integration-tests/ios/tests/app.ts
  integration-tests/ios/tests/login.ts
  integration-tests/ios/utils/init.ts
  src/app/(auth)/(tabs)/trivia/index.tsx
  src/app/(auth)/startTrivia/_layout.tsx
  src/app/(auth)/startTrivia/index.tsx
  src/app/(auth)/startTrivia/loading/_layout.tsx
  src/app/(auth)/startTrivia/loading/battle/_layout.tsx
  src/app/(auth)/startTrivia/loading/battle/index.tsx
  src/app/(auth)/startTrivia/loading/index.tsx
  src/components/trivia/PlayerStatus/index.tsx
  src/components/trivia/TriviaCardContainer/TriviaCard/Challenged/index.tsx
  src/components/trivia/TriviaCardContainer/TriviaCard/Incomplete/index.tsx
  src/components/trivia/TriviaCardContainer/TriviaCard/Pending/index.tsx
  src/components/trivia/TriviaCardContainer/TriviaCard/Waiting/index.tsx
  src/hooks/useTrivia.tsx
  src/redux/slice/trivia.slice.ts
Labels: bug
